[admiral]
items = ["left", "ws",
	"center", "clock",
	"right", "battery"]

[clock]
path = "date '+ %a %b %d, %T'"
reload = 1

[ws]
path = "./workspace.sh"

[battery]
path = "./battery.sh"
reload = 60


[left]
path = "echo '%{l}'"
static = true

[center]
path = "echo '%{c}'"
static = true

[right]
path = "echo '%{r}'"
static = true

